# Generated by Django 5.0.dev20230322073524 on 2023-03-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='DEFAULT VALUE', max_length=1000),
        ),
    ]
